version: '3.6'

services:
  server:
    container_name: stonks
    image: ghcr.io/myth/stonks:v1.0.1
    restart: unless-stopped
    volumes:
      - "./config.json:/app/config.json:ro"
      - "./history.db:/app/history.db"
